sudo: false
language: ruby
rvm:
  - 2.0.0
  - 2.1.3
  - 2.2.0
env:
  - DB=sqlite
  - DB=mysql
cache: bundler
before_script:
  - cp test/app/config/database.travis.yml test/app/config/database.yml
  - RAILS_ENV=test bundle exec rake db:create db:schema:load
script:
  - RAILS_ENV=test bundle exec rake test